version: '3.8'
services:
  av:
    container_name: go-address_validation
    build:
      context: .
      args: {}
      dockerfile: Dockerfile
      target: production
    depends_on: []
    env_file: .env
    environment: {}
    ports:
      - '3000:3000'
      - '3002:3001'
    volumes:
      - ./address_validation:/usr/src/app
  av-swagger:
    container_name: go-address_validation-swagger
    build:
      context: .
      args: {}
      dockerfile: Dockerfile
      target: swagger
    depends_on: []
    env_file: .env
    environment: {}
    ports:
      - '8081:8081'
    volumes:
      - ./address_validation:/usr/src/app
